service: boa-serverless-app

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

functions:
  hello:
    handler: index.handler
    events:
      - http:
          path: hello
          method: get
