name: Build and Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Lint
      run: npm run lint

    - name: Test
      run: npm test

    - name: Zip Files
      run: zip -r function.zip .

    - name: Configure AWS credentials
      run: |
        aws configure set aws_access_key_id <your-aws-access-key-id>
        aws configure set aws_secret_access_key <your-aws-secret-access-key>
        aws configure set default.region <your-aws-region>

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code --function-name <your-lambda-function-name> --zip-file fileb://function.zip
